version: '3.8'
services:
  streaming-video-downloader:
    container_name: 'streaming-video-downloader'
    image: 'ghcr.io/jmorbegoso/streaming-video-downloader:latest'
    restart: 'always'
    user: '1001:1001'
    environment:
      - 'TWITCH_CHANNELS=https://www.twitch.tv/twitch https://www.twitch.tv/xbox'
      - 'STREAM_QUALITY=best'
      - 'STREAM_OPTIONS=--twitch-disable-reruns --twitch-disable-ads'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '~/downloads:/output:rw'
